//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroMayor
    {
        public int ID { get; set; }
        public string Empresa { get; set; }
        public string CodigoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string FechaContabilizacion { get; set; }
        public string FechaVencimiento { get; set; }
        public string FechaDocumento { get; set; }
        public string Serie { get; set; }
        public string NumDocto { get; set; }
        public string NumFolio { get; set; }
        public string NumTransac { get; set; }
        public string Comentarios { get; set; }
        public string Proyecto { get; set; }
        public string CuentaContrap { get; set; }
        public string NombreCuenta { get; set; }
        public string Indicador { get; set; }
        public string CargoAbono { get; set; }
        public string Cargo { get; set; }
        public string Abono { get; set; }
        public string SaldoAcum { get; set; }
        public string SaldoVencido { get; set; }
        public string Debito { get; set; }
        public string Credito { get; set; }
        public string CentroCosto { get; set; }
        public string Temporada { get; set; }
        public string Campo { get; set; }
        public string Especievariedad { get; set; }
        public string AcuerdoGlobal { get; set; }
        public string NumSec { get; set; }
        public string TemporadaCabecera { get; set; }
    }
}
